# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 23:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20171205_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='assigned_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 23, 57, 5, 731071, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='complete_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 23, 57, 5, 731139, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='results_log',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 23, 57, 5, 731109, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='task_name',
            field=models.CharField(default='baseline', max_length=128),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='base.Task'),
        ),
    ]
