# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20171206_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='assigned_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='complete_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
