# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 02:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('week', models.IntegerField(choices=[(1, b'Melbourne'), (2, b'Manhattan'), (3, b'San Francisco'), (4, b'Portland'), (5, b'Philadelphia'), (6, b'Adelaide'), (7, b'Washington DC'), (8, b'Glasgow')], default=1)),
                ('level', models.IntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4')], default=1)),
                ('day', models.IntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5')], default=1)),
                ('slide_num', models.IntegerField(default=0)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
